### ISSUE TITLE
Stuck adding to cart

### ISSUE THREAD

**Issue by bryanjblake** [alexxsalazar/Nvidia3080_BB_bot#2]
I'm having trouble getting past adding to cart.  I think I may not be putting the correct cookie data in the sensor_data_cookie.txt file.  I pasted the data from the _abck cookie.  Is that the only cookie needed?

**Comment by alexxsalazar** [comment]
No copy all cookies once you find the 0 in the abck cookie. Make sure to change it every couple hours

**Comment by bryanjblake** [comment]
Ok and what are you using to copy the cookies?

**Comment by alexxsalazar** [comment]
You can use a lot of things. I personally use burp but it’s cause I like burp. I think there are even browser extensions that copy them as a whole string. Burp community version is free and a good tool. I think everyone should get an idea of the type of requests being made. Pretty cool. If you need help with it lemme know

**Comment by bryanjblake** [comment]
Awesome thank you!  Is the required format like the picture in the readme?

Cookie_name:value

No brackets, separators or anything? Just line breaks?  Thanks again for
your help

**Comment by alexxsalazar** [comment]
So the way I made it is to put it in as giant string seperated by ; per cookie. https://www.admin-magazine.com/var/ezflow_site/storage/images/archive/2014/19/searching-for-security-flaws-and-exploits-with-burp-suite/figure-3/99837-1-eng-US/Figure-3_reference.png . This is a like of what they look like in burp. If you'd like I can make it so that you can make it look like json but I personally found that copy and pasting as a string was easier. Sorry about the bad documentation I was just trying to post it as fast as possible. And yeah no worries feel free to ask anything I don't mind :)

**Comment by mikeekert** [comment]
document.cookie in the console should output something similar

**Comment by bryanjblake** [comment]
> So the way I made it is to put it in as giant string seperated by ; per cookie. https://www.admin-magazine.com/var/ezflow_site/storage/images/archive/2014/19/searching-for-security-flaws-and-exploits-with-burp-suite/figure-3/99837-1-eng-US/Figure-3_reference.png . This is a like of what they look like in burp. If you'd like I can make it so that you can make it look like json but I personally found that copy and pasting as a string was easier. Sorry about the bad documentation I was just trying to post it as fast as possible. And yeah no worries feel free to ask anything I don't mind :)

Ok awesome it works!  Can I update the cookies while the tasks are running?  Is the file only read during checkout?

> document.cookie in the console should output something similar

Thanks!  That worked.

**Comment by alexxsalazar** [comment]
Yep the task reads only during checkout so you are able to update while it is checking for stock!
