### ISSUE TITLE
Default to shipping?

### ISSUE THREAD

**Issue by snortlax** [alexxsalazar/Nvidia3080_BB_bot#5]
Is there a way to change the check out from local pickup to shipping?

Also, if I use the cookie AFTER I log in to bestbuy, I get "Error Starting Checkout (line 159 IndexError list index out of range)"
However check out process was successful when using fresh cookies from incognito (without logging in). However the resulting purchase was a "guest check out" with local pickup.

Was the guest check out intentional?

**Comment by alexxsalazar** [comment]
Yeah there's actually a call made in between to make it default to shipping but I didn't add it because I assumed that the 3080 wouldn't be in stock at a local shop. If it isn't available locally it defaults to your shipping location. As for the guest check out it was done intentionally. I don't want anyone's account to be banned. Let me know if you think I should change that

**Comment by snortlax** [comment]
I see! I tested the bot by picking an item that could be picked up at the store so seeing how the 3080s are online only so it should NOT be a problem.
I think you are right about being cautious about account ban but I was only getting one so I didn't think it would be an issue.
Nevertheless, I think your design is ideal, thank you for your time. Been trying everyday since it came out so this is my last resort. Fingers crossed!

**Comment by alexxsalazar** [comment]
Haha ty good luck! Lemme know if there's anything I can do :)
