### ISSUE TITLE
Privacy.com Spending Limits

### ISSUE THREAD

**Issue by vic18t** [alexxsalazar/Nvidia3080_BB_bot#9]
Hi Alex,

Privacy.com has spending limits on new accounts ($250 daily, $1000 monthly) which would make getting a 3080 impossible for new accounts. 

Will the bot still work with a regular credit card?

**Comment by alexxsalazar** [comment]
Hey!
Sorry about that! I think privacy.com calculates spending limits differently for everyone because I didn't have that problem. How it calculates I have no idea but it's probably something dumb like time bank account has been open or something. As for it working with credit cards it won't. I didn't want to risk my credit card while working on authenticating it with 3dsecure. There is sorta boilerplate code that you could try to get it working with but your card might start getting flagged. Sorry about that! Some people tried using a debit card and it worked for them so maybe you can try that out?

**Comment by vic18t** [comment]
Ok I did test it with a credit card and it said there was an error, but the transaction still went through and I got an order confirmation from Best Buy. Will that mean it will still work or does Best Buy reconcile these credit card transactions later if they look suspicious?

Privacy.com says the spending limit is for all new accounts.

**Comment by alexxsalazar** [comment]
As for privacy.com that’s weird even now my account is like 2 weeks old and the daily is a couple thousand. And for credit card transactions, if you look through the api calls it redirects them to 3dsecure and they handle the rest. The credit card working isn’t as reliable as the virtual card. I stopped working on it after a couple tries of adjusting a couple call sequences because I didn’t want to risk my credit card. That’s why the read me has that only virtual cards have been tested. Whether or not you want to try a credit card only is up to you

**Comment by vic18t** [comment]
Ya I don’t have much of a choice now but to use CC. I emailed Privacy.com to see if they can increase my daily spending limit.

**Comment by alexxsalazar** [comment]
Yeah sorry if it weren’t for me having sooo many recurring subscriptions on my card I would’ve worked on it. Replacing it would be too much of a pain
